### ISSUE TITLE
Could not find the euclidean distance based reward cache for the visual dialogue task

### ISSUE THREAD

**Issue by gaoqitong** [Sea-Snell/Implicit-Language-Q-Learning#4]
Dear authors,

Thank you for your great work as well as sharing this comprehensive code base. I was wondering if you could please share the euclidean distance based reward cache for the visual dialogue task, i.e., the point *ii* below as quoted from the documentation. I have downloaded the data.zip from the link to Google drive and it seems not to contain `[split]_rank_reward_cache2.json`. Thank you!

>reward_cache: Optional[str]=None – where the rewards for each dialogue are stored. If None, it will set all rewards to None. We provide caches for two reward functions:
>
>i.The reward for the percentile-rank reward function we used in our paper is cached at: data/vis_dialogue/processed/visdial_0.5/[split]_rank_reward_cache1.json, where [split] is replaced by one of train, val, or test.
>
>ii.The euclidean distance based reward used by the paper [Learning Cooperative Visual Dialog Agents with Deep Reinforcement Learning](https://arxiv.org/abs/1703.06585) is cached at: data/vis_dialogue/processed/visdial_0.5/[split]_reward_cache2.json, where [split] is replaced by one of train, val, or test.

**Comment by Sea-Snell** [comment]
Apologies, for leaving that one out of the data. I just uploaded an update to the data on google drive, which includes this requested file.
