### ISSUE TITLE
Error Running Monte Carlo Policy for Wordle

### ISSUE THREAD

**Issue by sarahlu0** [Sea-Snell/Implicit-Language-Q-Learning#6]
Hi. When I try to run the Wordle game using the monte carlo policy, I get an error, and it fails to run. I am using Python 3.9.7 on Ubuntu 22.04. 

Here is my terminal output:
![image](https://github.com/Sea-Snell/Implicit-Language-Q-Learning/assets/109558602/5b404ebb-ac4b-41dd-ae7d-b9c32b7ef0a4)

(I hope the screenshot works)
The code that I am running is composed of the playing Wordle script you provided (https://github.com/Sea-Snell/Implicit-Language-Q-Learning#playing-wordle), just edited with the basic monte carlo policy script (https://github.com/Sea-Snell/Implicit-Language-Q-Learning#montecarlopolicy), and stuff to output the reward. 

I appreciate any help you can provide to help fix this error. If you need more information, please don't hesitate to ask. 
Thanks!

**Comment by Sea-Snell** [comment]
I just pushed a fix! If you pull and try again it should work now. Sorry about that.

**Comment by sarahlu0** [comment]
Works now, thanks!
