### ISSUE TITLE
Question on indexing in Q loss 

### ISSUE THREAD

**Issue by DT6A** [Sea-Snell/Implicit-Language-Q-Learning#7]
Hello! Could you please explain me why in the Q loss function
https://github.com/Sea-Snell/Implicit-Language-Q-Learning/blob/0dc556150bfbdca5e1e6ee322c9126486c2162f7/src/models/iql_model.py#L355
we have this multiplication: `(1 - terminals[:, 1:]) * vns`? Shouldn't it be `(1 - terminals[:, :-1]) * vns`?  If code is correct what is the logic behind indexing than?

**Comment by Sea-Snell** [comment]
Hi, thanks for the question.

`terminals` is size T
`vns` is size `T-1`

vns corresponds to the "values at the next step", so the `T-1` is excluding the first step. So we want to right shift the terminals to get the values that correspond with vns.

Apologies for the confusion about this. Let me know if you have other questions or want me to further clarify things.

**Comment by DT6A** [comment]
Thanks for you answer. Usually in RL terminals are used to stop Bellman update propagation after episode is finished. So terminal at step `t` usually indicates whether the step `t` is terminal. But in your case we are shifting terminals to the left by one, so terminal will affect the step before the last one and Bellman signal (next V value) from the last step is not propagated to it. This is true if your indexing is not different from how it's usually done in RL. Sorry if I'm missing something. It would be great if you indicate me what I misunderstand. 

Everything is fine if you consider `terminal[t]` as a flag that `t - 1` was the last step. But when looking at other parts of the code it doesn't seem like that.

**Comment by Sea-Snell** [comment]
Ok to give a concrete example:

Say I have a sequence of tokens:
`a b c d e`

The corresponding terminals are:
0 0 0 0 1

The vns are:
-1 -2 -3 -4

These vns correspond to:
vns: -1; input tokens: `a b`; terminal: 0
vns: -2; input tokens: `a b c`; terminal: 0
vns: -3; input tokens: `a b c d`; terminal: 0
vns: -4; input tokens: `a b c d e`; terminal: 1

The last step here is being masked in the backup. The last action in the sequence occurs with input tokens: `a b c d`, which has an action of `e`, and transitions to the final state `a b c d e`, which corresponds to the last vns, which is masked.

**Comment by DT6A** [comment]
But vns are already shifted here:
https://github.com/Sea-Snell/Implicit-Language-Q-Learning/blob/0dc556150bfbdca5e1e6ee322c9126486c2162f7/src/models/iql_model.py#L399
I think that is what confuses me.

**Comment by DT6A** [comment]
Thanks for example. But we don't process this part:
vns: `some value`; input tokens: `a` ; terminal: 0
That is what confuses me. If it is expected to be ignored than everything is fine. But why do we ignore it?

**Comment by Sea-Snell** [comment]
because it is the "initial state" we fit the Q value at input tokens: `a` ; terminal: 0 to the vns at input tokens `a b`. We don't need vns at the start state, since it is not a "next state". Hence we can ignore it. Does that make sense?

**Comment by DT6A** [comment]
In this case yes. Thank you very much for your answers!
