### ISSUE TITLE
Question about stds reported in the paper

### ISSUE THREAD

**Issue by DT6A** [Sea-Snell/Implicit-Language-Q-Learning#9]
Hello!

Could you please explain how stds for performance are calculated in your paper? In RL std is usually reported over different training seeds but I haven't seen the seed argument for the training. I also didn't find information about it in the paper.

**Comment by Sea-Snell** [comment]
Ah, yes the std is the standard error of the reward during evaluation. This is not related to training multiple models with different random seeds. Concretely if I evaluate my model on N rollouts, where R_N is a vector of the total reward for each of the N rollouts, I report `np.mean(R_N) +- np.std(R_N) / np.sqrt(N)`

**Comment by DT6A** [comment]
Got it. Thanks for your answer!
